version: '3.9'

services:
  web:
    container_name: web
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:7000"
    volumes:
      - .:/riade/django_docker_student
    ports:
      - "7000:7000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=stundent_docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123321
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata: